removed hack in install-user-from-scratch script

diff --git a/install-user-from-scratch b/install-user-from-scratch
--- a/install-user-from-scratch
+++ b/install-user-from-scratch
@@ -49,14 +49,9 @@ echo "$ME: Starting librina phase"
     echo "$ME: Cannot bootstrap"
     exit 1
 }
-# (mkdir -p $BUILDDIR/librina && cd $BUILDDIR/librina && $SRCDIR/librina/configure --enable-java-bindings $FLAGS --with-sysheaders=$SRCDIR/linux/usr/include --prefix=$PREFIX && make $MAKEFLAGS clean install installcheck) || {
-#     echo "$ME: Cannot complete librina phase"
-#     exit 1
-# }
-
-(mkdir -p $BUILDDIR/librina && cd $BUILDDIR/librina && $SRCDIR/librina/configure --enable-java-bindings $FLAGS --with-sysheaders=/pristine/headers/include --prefix=$PREFIX && make $MAKEFLAGS clean install installcheck) || {
-    echo "$ME: Cannot complete librina phase"
-    exit 1
+(mkdir -p $BUILDDIR/librina && cd $BUILDDIR/librina && $SRCDIR/librina/configure --enable-java-bindings $FLAGS --with-sysheaders=$SRCDIR/linux/usr/include --prefix=$PREFIX && make $MAKEFLAGS clean install installcheck) || {
+     echo "$ME: Cannot complete librina phase"
+     exit 1
 }
 
 echo "$ME: Starting rinad phase"
