scripts: fixed wrong identation

diff --git a/install-user-from-scratch b/install-user-from-scratch
--- a/install-user-from-scratch
+++ b/install-user-from-scratch
@@ -50,8 +50,8 @@ echo "$ME: Starting librina phase"
     exit 1
 }
 (mkdir -p $BUILDDIR/librina && cd $BUILDDIR/librina && $SRCDIR/librina/configure --enable-java-bindings $FLAGS --with-sysheaders=$SRCDIR/linux/usr/include --prefix=$PREFIX && make $MAKEFLAGS clean install installcheck) || {
-     echo "$ME: Cannot complete librina phase"
-     exit 1
+    echo "$ME: Cannot complete librina phase"
+    exit 1
 }
 
 echo "$ME: Starting rinad phase"
