Fixes #122

diff --git a/install-from-scratch b/install-from-scratch
--- a/install-from-scratch
+++ b/install-from-scratch
@@ -11,6 +11,14 @@ PREFIX=`echo "$1"|sed -e "s,\/$,,"`
 
 echo "$ME: Prefix is \`$PREFIX'"
 
+mkdir -p $PREFIX || {
+    echo "$ME: Cannot create directory \`$PREFIX'"
+}
+
+#
+# FIXME: we should definitely do a VPATH build ...
+#
+
 #echo "$ME: Starting kernel phase"
 #(cd linux && INSTALL_PATH=$PREFIX/boot INSTALL_MOD_PATH=$PREFIX make bzImage modules modules_install install) || {
 #    echo "$ME: Cannot complete kernel phase"
@@ -18,19 +26,19 @@ echo "$ME: Prefix is \`$PREFIX'"
 #}
 
 echo "$ME: Starting librina phase"
-(cd librina && ./bootstrap && ./configure --enable-java-bindings --prefix=$PREFIX && make install) || {
+(cd librina && ./bootstrap && ./configure --enable-java-bindings --prefix=$PREFIX && make clean install) || {
     echo "$ME: Cannot complete librina phase"
     exit 1
 }
 
 echo "$ME: Starting rinad phase"
-(cd rinad && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX && make install) || {
+(cd rinad && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX && make clean install) || {
     echo "$ME: Cannot complete rinad phase"
     exit 1
 }
 
 echo "$ME: Starting rina-tools phase"
-(cd rina-tools && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX  && make install) || {
+(cd rina-tools && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX  && make clean install) || {
     echo "$ME: Cannot complete rina-tools phase"
     exit 1
 }
